/**
 * Copyright 2026 Project LLZK
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include "Analysis/SymbolicStore.h"
#include <llvm/Support/LogicalResult.h>
#include <llzk/Dialect/Struct/IR/Ops.h>
#include <llzk/Util/Field.h>

namespace lleq {

/// The driver class for lightweight symbolic verification, this constructs a
/// `SymbolicStore` for a given 'struct.def' and then uses symbolic equivalence
/// to prove pairs of witness/constraint signals equivalent. The equivalent
/// signal pairs generated by this verifier can further be extracted into
/// extra assertions for deductive verification.
class SymbolicVerifier {
  llzk::component::StructDefOp structDef;
  SymbolicStore store;

public:
  SymbolicVerifier(llzk::component::StructDefOp structDef)
      : structDef{structDef} {}

  /// Build a mapping of struct signal names to symbolic expressions
  llvm::LogicalResult buildStore();

  /// Attempt to prove symbolic equivalence of a given member's
  /// witness/constraint pair
  bool areEquivalent(llvm::StringRef memberName);

  /// Generate symbolic equivalence assertions for the deductive verifier. Note
  /// that this generates assertions for *all members* (not just signals), since
  /// equivalence of some intermediate member might end up being a useful
  /// theorem for the solver
  llvm::SmallVector<std::string> generateAssertions(llzk::Field field);
};

} // namespace lleq
