name: Run Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        compiler:
          - name: GCC
            derivation: ".#withGCC"
            report: gcc-report.xml
          - name: Clang
            derivation: ".#withClang"
            report: clang-report.xml
    runs-on: ubuntu-24.04
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persistent-credentials: false
      - uses: cachix/install-nix-action@v31.11.0
        with:
          install_url: https://releases.nixos.org/nix/nix-2.23.3/install
          github_access_token: "${{secrets.GITHUB_TOKEN}}"
      - name: Set Git credentials
        run: |
          git config --global 'url.https://api@github.com/'.insteadOf 'https://github.com/'
          git config --global 'url.https://ssh@github.com/'.insteadOf 'ssh://github.com/'
          git config --global 'url.https://git@github.com/'.insteadOf 'git@github.com/'
      - uses: cachix/cachix-action@v17
        with:
          name: veridise-public
          authToken: "${{secrets.CACHIX_AUTH_TOKEN}}"
      - name: "Build with ${{matrix.compiler.name}}"
        run: "nix --print-build-logs build '${{matrix.compiler.derivation}}'"
